# Menu
menu:
  Home: /
  Archives: /archives/index.html
  Gallery: /gallery/index.html
  About: /about/index.html
rss: /atom.xml


# Miscellaneous
favicon: /favicon.ico
brand: /images/shark.svg

# Ocean Video
# Because I put videos in multiple formats on the same path, I just labeled the path here.
ocean:
  overlay: true
  path: /images/ocean/
  brand: /images/shark-inverted.svg

# Content
excerpt_link: Read More...
share_text: Share
search_text: Search
nav_text:
  page_prev: Prev page
  page_next: Next page
  post_prev: Newer posts
  post_next: Olde posts

# Tags
show_count: false

# Toc
toc: true

# fancybox
fancybox: true

# Gitalk
gitalk:
  enable: false # true
  clientID: # GitHub Application Client ID
  clientSecret: # Client Secret
  repo: # Repository name
  owner: # GitHub ID
  admin: # GitHub ID

search:
  path: search.xml
  field: post
  content: true